config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/show'
  get 'customers/new'
  get 'customers/create'
  get 'customers/edit'
  get 'customers/update'
  get 'customers/destroy'
  get 'customers/book'
  get 'pages/bigmap', to: 'pages#bigmap'
  get 'pages/home', to: 'pages#home'
  get 'pages/operations', to: 'pages#operations'
  get 'pages/airplus', to: 'pages#airplus'
  get 'flights/stations', to: 'flights#stations'
  get 'geocoding/show', to: 'geocoding#show'
  get 'geocoding/geocode', to: 'geocoding#geocode'
  get 'flights/index'
  get 'flights/show'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/destroy'
  get 'flights/update'
  get 'registrations/index'
  get 'registrations/show'
  get 'registrations/new'
  get 'registrations/create'
  get 'registrations/edit'
  get 'registrations/update'
  get 'registrations/destroy'
  get 'pages/operations'
  get 'flights/available_registrations', to: 'flights#available_registrations'
  get 'flights/available_aircrafts', to: 'flights#available_aircrafts', as: 'flights_available_aircrafts'
  get 'customers/list', to: 'customers#list', as: 'customers_list'
  get 'flights/:flight_id/customers', to: 'customers#flight_customers', as: 'flight_customers'
 
  root to: 'pages#airplus'
 

  resources :aircrafts
  resources :cabins
  resources :seats
  resources :registrations
  resources :flights
  resources :hauls
  resources :stations
  resources :airline_codes
  resources :customers

   post 'customers/reset_search', to: 'customers#reset_search'
 
  resources :flights do
    member do
      post 'create_return'
    end
  end

  resources :flights do
    collection do
      get :available_aircrafts
    end
  end

  

  
  
end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
 
    before_validation :upcase_acft
    validate :unique_acft
    validates :acft, length: { within: 4..4 }
    validates :acft, presence: true
    validates :acft, format: { with: /\A[a-zA-Z][0-9]+\z/,
    message:   "doit commencer par une lettre et être suivi de 3 chiffres" }
    has_many :flights, dependent: :destroy
    belongs_to :haul
  
    
   
#_________________________________________________________________________________
   private

     def unique_acft
        existing_acft = Aircraft.pluck(:acft) # Récupère tous les numéros existants dans la base de données
        pp "test" *100
        if existing_acft.include?(acft)
          errors.add(:acft, ":  Le code #{self.acft} est déjà utilisé.")
        end
      end

      def upcase_acft
        self.acft = acft.upcase if acft.present?
      end 

      


end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController

    before_action :set_aircraft, only: [:show, :edit, :update, :destroy]

    


    def index
        @aircrafts = Aircraft.all
    end

    def show
    end

    def new
    @aircrafts = Aircraft.all
    @aircraft = Aircraft.new
    @hauls = Haul.all
   
    
    end

    def create 
        @aircraft = Aircraft.new(params_aircraft)
       if @aircraft.save
        redirect_to @aircraft, notice: 'Aircraft was successfully created.'
        else
             @hauls = Haul.all
            render :new

       end
    end

    def edit
    end

    def update
        if @aircraft.update(params_aircraft)
            redirect_to @aircraft, notice: 'Aircraft was successfully updated.'
          else
            render :edit
          end
    end

    def destroy
      
            pp "A"*100
                if @aircraft.flights.any?
                  flash[:alert] = "This aircraft is used by flights and cannot be deleted."
                  else
                    @aircraft.destroy
                    flash[:notice] = "Aircraft type was successfully deleted."
                end
                redirect_to aircrafts_url
             
    end

    private

        def set_aircraft
            @aircraft = Aircraft.find(params[:id])
        end

        def params_aircraft
            params.require(:aircraft).permit(:acft, :aircraft_class, :seats, :registration, :haul, :haul_id) # Liste des attributs que vous utilisez
        end
    


end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/views/aircrafts/index.html.erb
<div class="container mt-10">
   <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <td>Aircraft type</td>
                    <td>Aircraft haul</td>
                </tr>
            </thead>

                <tbody>
                    <%  @aircrafts.each do |aircraft| %>
                    <tr>
                        <td><%= aircraft.acft %></td>
                    
                        <td><%= aircraft.haul.name %></td>


                        <td>
                            <%=link_to"Annuler type avion", aircraft_path(aircraft),method: :delete, class: "btn btn-danger btn-margin"%>
                            
                        </td>
                    </tr>
                     <% end %>
                   
                </tbody>

        </table>

        <span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 












   </div> 












</div>

app/views/aircrafts/new.html.erb
<div class="container col-12">

    <div class="bordered">
      
        <% if @aircrafts.present? %>

                    <h4>Aircraft(s) déjà créés :</h4>
                         <%= @aircrafts.map { |aircraft| "#{aircraft.acft} #{aircraft.haul.name}" }.join(', ') %>
           <%else%>
                <div class="alert alert-danger">
                    No aircraft, create it.
                </div>
        <% end %>
    </div>

    

            <div class="int1">
            <h1>Create Aircraft Type</h1>
            </div>

            <div class="row">
                <div class="col-4 mt-5">
                    <%= simple_form_for(@aircraft) do |f| %>
                        <div class="col-2.5">
                            <%=  f.label :acft,content_tag(:strong, 'Aircraft type:') %>
                            <%=  f.text_field :acft, class:"rounded-box"%>
                        </div>
                        <br><br>
                        <div class="col-2.5">
                            <%= f.label :haul_id, content_tag(:strong, 'Aircraft  haul:') %>
                           <%= f.collection_select :haul_id, @hauls, :id, :name, { prompt: 'Select Haul' }, class: "rounded-box" %>
                        </div>
                        <br>
                        
                        <br><br>
                        <div class="submit">
                            <%=f.submit"Valider", class: "btn btn-primary"%>
                        </div>   
                        <br><br>
                        <span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 
                    <%end%>
                        <% if @aircraft.errors.any? %>
                            <div id="error_explanation">
                                <h2><%= pluralize(@aircraft.errors.count, "error") %> </h2>
                                <ul>
                                    <% @aircraft.errors.full_messages.each do |message| %>
                                        <li><%= message %></li>
                                    <% end %>
                                </ul>
                            </div>
                        <% end %>

                </div>
            </div>
</div>

app/views/aircrafts/show.html.erb
<div class="container">
    <p> <strong>Type avion = </strong> <%= @aircraft.acft %></p>
    <p> <strong>Type haul = </strong> <%= @aircraft.haul.name %></p>
</div>
<span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 