config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/show'
  get 'customers/new'
  get 'customers/create'
  get 'customers/edit'
  get 'customers/update'
  get 'customers/destroy'
  get 'customers/book'
  get 'pages/bigmap', to: 'pages#bigmap'
  get 'pages/home', to: 'pages#home'
  get 'pages/operations', to: 'pages#operations'
  get 'pages/airplus', to: 'pages#airplus'
  get 'flights/stations', to: 'flights#stations'
  get 'geocoding/show', to: 'geocoding#show'
  get 'geocoding/geocode', to: 'geocoding#geocode'
  get 'flights/index'
  get 'flights/show'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/destroy'
  get 'flights/update'
  get 'registrations/index'
  get 'registrations/show'
  get 'registrations/new'
  get 'registrations/create'
  get 'registrations/edit'
  get 'registrations/update'
  get 'registrations/destroy'
  get 'pages/operations'
  get 'flights/available_registrations', to: 'flights#available_registrations'
  get 'flights/available_aircrafts', to: 'flights#available_aircrafts', as: 'flights_available_aircrafts'
  get 'customers/list', to: 'customers#list', as: 'customers_list'
  get 'flights/:flight_id/customers', to: 'customers#flight_customers', as: 'flight_customers'
 
  root to: 'pages#airplus'
 

  resources :aircrafts
  resources :cabins
  resources :seats
  resources :registrations
  resources :flights
  resources :hauls
  resources :stations
  resources :airline_codes
  resources :customers

   post 'customers/reset_search', to: 'customers#reset_search'
 
  resources :flights do
    member do
      post 'create_return'
    end
  end

  resources :flights do
    collection do
      get :available_aircrafts
    end
  end

  

  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :bookings, dependent: :nullify
  has_many :flights, through: :bookings

  before_validation :upcase_name
  before_validation :capitalize_first_name

  scope :active, -> { where(deleted_at: nil) }

  def soft_delete
    update(deleted_at: Time.current)
  end

  def deleted?
    deleted_at.present?
  end

  private

  def upcase_name
    self.name = name.upcase if name.present?
  end 

  def capitalize_first_name
    self.first_name = first_name.capitalize if first_name.present?
  end 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :destroy]
  
  def index
    @customers = Customer.all

  end

  def show
  end

  def new
    @customer = Customer.new
    if params[:flight_id].present?
      @flight = Flight.find(params[:flight_id])
    else
      redirect_to customers_book_path, notice: 'Please select a flight first.'
    end
  end

  def create
    @customer = Customer.new(params_customer)
    @flight = Flight.find(params[:flight_id])

    if @customer.save
      booking = Booking.create(customer: @customer, flight: @flight)
      redirect_to @customer, notice: 'Customer was successfully booked on the flight.'
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  #def destroy
   # customer = Customer.find(params[:id])
    #customer.bookings.discard_all
    #customer.bookings.update_all(status: 'cancelled')
    #customer.bookings.destroy_all
    #customer.destroy
    #redirect_to customers_url, notice: "Customer successfully destroyed."
    #def destroy
      #ActiveRecord::Base.transaction do
       # customer = Customer.find(params[:id])
       # customer.bookings.update_all(status: 'cancelled')
       # customer.destroy  # Use the standard destroy method
     # end
     # redirect_to customers_url, notice: "Customer successfully destroyed."
    #rescue ActiveRecord::RecordNotFound
      #redirect_to customers_url, alert: "Customer not found."
    #rescue => e
      #redirect_to customers_url, alert: "An error occurred: #{e.message}"
    #end
    def destroy
      ActiveRecord::Base.transaction do
        customer = Customer.find(params[:id])
        customer.bookings.update_all(status: 'cancelled')
        customer.soft_delete
        customer.destroy
      end
      redirect_to customers_url, notice: "Customer successfully marked as deleted."
    rescue ActiveRecord::RecordNotFound
      redirect_to customers_url, alert: "Customer not found."
    rescue => e
      redirect_to customers_url, alert: "An error occurred: #{e.message}"
    end
 

  def book
        @q = Flight.ransack(params[:q])
        @flights = if params[:q].present?
          @q.result.includes(:airline_code, :registration, :aircraft, :haul, :cabin, :seat, :departure_station, :arrival_station)
        else
          Flight.none # Ne renvoie aucun vol initialement
        end
    
        @aircrafts = Aircraft.all
        @airlineCodes = AirlineCode.all
        @Stations = Station.all
  end

  def reset_search
    @flights = Flight.none
    render json: { status: 'success' }
  end

  def list 
   
    @q = Flight.ransack(params[:q])
    @flights = if params[:q].present?
      @q.result.includes(:airline_code, :registration, :aircraft, :haul, :cabin, :seat, :departure_station, :arrival_station)
    else
      Flight.none # Ne renvoie aucun vol initialement
    end

    @aircrafts = Aircraft.all
    @airlineCodes = AirlineCode.all
    @Stations = Station.all
  end

  def flight_customers
    #@flight = Flight.find(params[:flight_id])
    #pp "8"*100
    #logger.debug "@flighttttttttttttt: #{@flight.inspect}"
    #@customers = @flight.customers
    #pp "9"*100
    #logger.debug "@customersttttttttttttt: #{@customers.inspect}"
    @flight = Flight.find(params[:flight_id])
    @customers = @flight.customers.includes(:bookings)
                        .where(bookings: { status: 'active' })
  end
  private

  def set_customer
    @customer = Customer.find(params[:id]) 
 end

  def params_customer
    params.require(:customer).permit(:name,  :first_name) # Liste des attributs que vous utilisez
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/book.html.erb
<% if @flights.any? %>
<% pp "5" * 100 %>
  <% puts "Il y a des vols disponibles : #{@flights.inspect}" %>
<% else %>

<% pp "6" * 100 %>
  <% puts "Aucun vol disponible." %>
<% end %>

    <div class="container col-12 mt-50">

        <h1>Book flights</h1>
        <div class="search ramsaq" data-controller="form-reset">
        
          <%= search_form_for @q, url: customers_book_path, method: :get, html: { data: { target: 'form-reset.form' } } do |form| %>
            <div class="row">
              <div class="form-group search-field col">
                <%= form.label :departure_date, "Date de départ" %>
                <%= form.date_select :departure_date_eq, {
                  order: [:day, :month, :year],
                  start_year: Date.current.year,
                  end_year: Date.current.year + 1,
                prompt: { day: "Day", month: "Month", year: "Year" }
                }, class: "form-control custom-width date-select-centered", style: "width: 100px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :airline_code_code_cont, "Code compagnie?" %>
                <%= form.collection_select :airline_code_id_eq, @airlineCodes, :id, :code, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :aircraft_acft_cont, "Type d'avion?" %>
                <%= form.collection_select :aircraft_id_eq, @aircrafts, :id, :acft, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :departure_station_name_cont, "Station de départ?" %>
                <%= form.collection_select :departure_station_id_eq, @Stations, :id, :name, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :arrival_station_name_eq, "Station d'arrivée?" %>
                <%= form.collection_select :arrival_station_id_eq, @Stations, :id, :name, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
            </div>
            <br><br>
            <div class="form-group">
              <%= form.submit class: "btn btn-primary btn-sm" %>
              <%= button_tag(type: 'button', class: 'btn btn-danger btn-sm', 'data-action': 'form-reset#reset') do %>
                Réinitialiser
              <% end %>
            </div>
          <% end %>
        </div>
        
        
    
    

      <div class="index row col-12" style="margin-top: 50px;">
         <table class="table table-bordered" style= "width:1500PX; border: 4px solid black;">
           
             <thead>
                 <tr>
                    <th class="text-center code">Code</th>
                    <th class="text-center"> Nbr</th>
                    <th class="text-center">Reg</th>
                    <th class="text-center">Type</th>
                    <th class="text-center">Network</th>
                    <th class="text-center">Cabin</th>
                    <th class="text-center">Seats</th>
                    <th class="text-center">Dpt </th>
                    <th class="text-center">Arrvl </th>
                     <th class="text-center">Dpt dte</th>
                     <th class="text-center">Arrvl dte</th>
                 </tr>
             </thead>
 
                 <tbody class="search">
                     <%  @flights.each do |flight| %>
                        <tr>
                            <td class="text-center"><%= flight.airline_code.code %></td>
                            <td class="text-center"><%= flight.flight_number %></td>
                            <td class="text-center"><%= flight.registration.reg %></td>
                            <td class="text-center"><%= flight.aircraft.acft %></td>
                            <td class="text-center"><%= flight.haul.name %></td>
                            <td class="text-center"><%= flight.cabin.cbn %></td>
                            <td class="text-center"><%= flight.seat.number %></td>
                            <td class="text-center"><%= flight.departure_station.name %></td>
                            <td class="text-center"><%= flight.arrival_station.name %></td>
                            <td class="text-center"><%= l(flight.departure_date, format: :default) %></td>
                            <td class="text-center"><%= l(flight.arrival_date, format: :default) %></td>
                         <td>
                             <%= link_to "Book Flight", new_customer_path(flight_id: flight.id), class: "btn btn-success btn-margin" %>
                           
                              
          
                         </td>
                       </tr>
                    <% end %>
                    
                 </tbody>
 
         </table>
        </div>



         <br>

        <div class="link">
          <span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 
          <span><%=link_to"Book again", customers_book_path, class: "btn btn-danger btn-margin"%></span>
          <span><%= link_to "Customers list", customers_list_path, class: "btn btn-primary" %></span>
        </div>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/destroy.html.erb
<h1>Customers#destroy</h1>
<p>Find me in app/views/customers/destroy.html.erb</p>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/flight_customers.html.erb
<div class="container">
    



        <h1 class="titre">Customers for Flight <%= @flight.flight_number %></h1>

        <table class="table customers">
        <thead>
            <tr>
            <th>Name</th>
            <th>First Name</th>
            <th>Annuler</th>
            </tr>
        </thead>
        <tbody>
            <% @customers.each do |customer| %>
            <tr>
                <td><%= customer.name %></td>
                <td><%= customer.first_name %></td>
                <td>
                    <%=link_to"Annuler", customer_path(customer),method: :delete,class: "btn btn-danger btn-margin"%>
                </td>
             
            </tr>
           
            <% end %>
        </tbody>
        </table>

        <%= link_to 'Back to Manage bookings', customers_list_path, class: 'btn btn-primary' %>

    </div>

app/views/customers/index.html.erb
<div class="container mt-10">

    <div class="row">

        <table class="table">

            <thead>
                <tr>
                    <td>Name</td>
                    <td>First name</td>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <% @customers.each do |customer| %>
                        <td><%= customer.name %></td>
                        <td><%= customer.first_name  %></td>
                    </tr>
                    <% end %>
                </tbody>

        </table>
        <span><%= link_to "Home", pages_airplus_path, class: "btn btn-primary" %></span>

    </div>

</div>

app/views/customers/list.html.erb
<% if @flights.any? %>
<% pp "5" * 100 %>
  <% puts "Il y a des vols disponibles : #{@flights.inspect}" %>
<% else %>

<% pp "6" * 100 %>
  <% puts "Aucun vol disponible." %>
<% end %>

    <div class="container col-12 mt-50">

        <h1>Manage bookings</h1>
        <div class="search ramsaq" data-controller="form-reset">
        
          <%= search_form_for @q, url: customers_list_path, method: :get, html: { data: { target: 'form-reset.form' } } do |form| %>
            <div class="row">
              <div class="form-group search-field col">
                <%= form.label :departure_date, "Date de départ" %>
                <%= form.date_select :departure_date_eq, {
                  order: [:day, :month, :year],
                  start_year: Date.current.year,
                  end_year: Date.current.year + 1,
                prompt: { day: "Day", month: "Month", year: "Year" }
                }, class: "form-control custom-width date-select-centered", style: "width: 100px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :airline_code_code_cont, "Code compagnie?" %>
                <%= form.collection_select :airline_code_id_eq, @airlineCodes, :id, :code, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :aircraft_acft_cont, "Type d'avion?" %>
                <%= form.collection_select :aircraft_id_eq, @aircrafts, :id, :acft, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :departure_station_name_cont, "Station de départ?" %>
                <%= form.collection_select :departure_station_id_eq, @Stations, :id, :name, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
              <div class="form-group search-field col">
                <%= form.label :arrival_station_name_eq, "Station d'arrivée?" %>
                <%= form.collection_select :arrival_station_id_eq, @Stations, :id, :name, { include_blank: "Select" }, class: "form-control custom-width date-select-centered", style: "width: 95px;" %>
              </div>
            </div>
            <br><br>
            <div class="form-group">
              <%= form.submit class: "btn btn-primary btn-sm" %>
              <%= button_tag(type: 'button', class: 'btn btn-danger btn-sm', 'data-action': 'form-reset#reset') do %>
                Réinitialiser
              <% end %>
            </div>
          <% end %>
        </div>
        
        
    
    

      <div class="index row col-12" style="margin-top: 50px;">
         <table class="table table-bordered" style= "width:1500PX; border: 4px solid black;">
           
             <thead>
                 <tr>
                    <th class="text-center code">Code</th>
                    <th class="text-center"> Nbr</th>
                    <th class="text-center">Reg</th>
                    <th class="text-center">Type</th>
                    <th class="text-center">Network</th>
                    <th class="text-center">Cabin</th>
                    <th class="text-center">Seats</th>
                    <th class="text-center">Dpt </th>
                    <th class="text-center">Arrvl </th>
                     <th class="text-center">Dpt dte</th>
                     <th class="text-center">Arrvl dte</th>
                 </tr>
             </thead>
 
                 <tbody class="search">
                     <%  @flights.each do |flight| %>
                        <tr>
                            <td class="text-center"><%= flight.airline_code.code %></td>
                            <td class="text-center"><%= flight.flight_number %></td>
                            <td class="text-center"><%= flight.registration.reg %></td>
                            <td class="text-center"><%= flight.aircraft.acft %></td>
                            <td class="text-center"><%= flight.haul.name %></td>
                            <td class="text-center"><%= flight.cabin.cbn %></td>
                            <td class="text-center"><%= flight.seat.number %></td>
                            <td class="text-center"><%= flight.departure_station.name %></td>
                            <td class="text-center"><%= flight.arrival_station.name %></td>
                            <td class="text-center"><%= l(flight.departure_date, format: :default) %></td>
                            <td class="text-center"><%= l(flight.arrival_date, format: :default) %></td>
                         <td>
                            <%= link_to "Customers list", flight_customers_path(flight), class: "btn btn-success btn-sm" %>
                         </td>
                       </tr>
                    <% end %>
                    
                 </tbody>
 
         </table>
        </div>



         <br>

        <div class="link">
          <span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 
          <span><%=link_to"Book again", customers_book_path, class: "btn btn-danger btn-margin"%></span>
        </div>

app/views/customers/new.html.erb
<div class="container col-12">
      <div class="int1">
        <h1>Book Customer for Flight <%= @flight.flight_number %></h1>
      </div>
      
      <div class="row">
        <div class="col-3 mt-5">
          <%= simple_form_for(@customer, url: customers_path(flight_id: @flight.id)) do |f| %>
            <div class="col-2.5">
              <%= f.label :name, content_tag(:strong, 'Name passenger:') %>
              <%= f.text_field :name, class: "rounded-box" %>
            </div>
            <br><br>
            <div class="col-2.5">
              <%= f.label :first_name, "<strong>Firstname passenger:</strong>".html_safe %>
              <%= f.text_field :first_name, class: "rounded-box" %>
            </div>
            <br><br>
            <div class="submit">
              <%= f.submit "Valider", class: "btn btn-primary" %>
            </div>
            <br><br>
            <span><%= link_to "AIR PLUS front page", pages_airplus_path, class: "btn btn-primary mx-2" %></span>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/customers/show.html.erb
<div class="container">
    <p> <strong>Name = </strong> <%= @customer.name %></p>
    <p> <strong>First name = </strong> <%= @customer.first_name %></p>
</div>
<span><%=link_to"Home",customers_new_path,class: "btn btn-primary" %></span> 

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>