config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/show'
  get 'customers/new'
  get 'customers/create'
  get 'customers/edit'
  get 'customers/update'
  get 'customers/destroy'
  get 'customers/book'
  get 'pages/bigmap', to: 'pages#bigmap'
  get 'pages/home', to: 'pages#home'
  get 'pages/operations', to: 'pages#operations'
  get 'pages/airplus', to: 'pages#airplus'
  get 'flights/stations', to: 'flights#stations'
  get 'geocoding/show', to: 'geocoding#show'
  get 'geocoding/geocode', to: 'geocoding#geocode'
  get 'flights/index'
  get 'flights/show'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/destroy'
  get 'flights/update'
  get 'registrations/index'
  get 'registrations/show'
  get 'registrations/new'
  get 'registrations/create'
  get 'registrations/edit'
  get 'registrations/update'
  get 'registrations/destroy'
  get 'pages/operations'
  get 'flights/available_registrations', to: 'flights#available_registrations'
  get 'flights/available_aircrafts', to: 'flights#available_aircrafts', as: 'flights_available_aircrafts'
  get 'customers/list', to: 'customers#list', as: 'customers_list'
  get 'flights/:flight_id/customers', to: 'customers#flight_customers', as: 'flight_customers'
 
  root to: 'pages#airplus'
 

  resources :aircrafts
  resources :cabins
  resources :seats
  resources :registrations
  resources :flights
  resources :hauls
  resources :stations
  resources :airline_codes
  resources :customers

   post 'customers/reset_search', to: 'customers#reset_search'
 
  resources :flights do
    member do
      post 'create_return'
    end
  end

  resources :flights do
    collection do
      get :available_aircrafts
    end
  end

  

  
  
end

app/views/pages/airplus.html.erb
<body class="custom-background">
    <div class="container text-center">
        <div class="row my-4">
            <div class="col">
                <p class="airplus">AIR PLUS </p>
                <p class="airplus">CUSTOMER PAGE </p>
            </div>
        </div>

        
        <div class="test">
            <span><%= link_to "Operations", pages_operations_path, class: "btn btn-primary" %></span>
            <span><%= link_to "Book flight", customers_book_path, class: "btn btn-primary" %></span>
            <span><%= link_to "Manage bookings", customers_list_path, class: "btn btn-primary" %></span>
        </div>
            
        </div>
    </div>
</body>

app/views/pages/bigmap.html.erb
 <body>
        <div class="container ">
        
            <div class="map" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
                <div id='map' style='width: 1000px; height: 900px; margin: auto;'></div>
            </div>

            <script>
                mapboxgl.accessToken = "pk.eyJ1IjoicG5nYXV0aGllciIsImEiOiJjbHFncjBjMG0xZGNlMm1ubWV2aXU1NnpmIn0.x06uuDfCgcRIZtJNmrF7Bg";
                const coordinates = [2.549324, 49.008468];
                const map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/mapbox/streets-v12',
                    center: coordinates,
                    zoom: 2
                });

                map.on('load', function() {
                    // Itérer sur chaque station et ajouter un marqueur
                    <% @stations_coordinates.each do |coordinates| %>
                        <% if coordinates %>
                            new mapboxgl.Marker({
                                scale: 0.6,
                                color: '#fc0339'
                            })
                            .setLngLat([<%= coordinates[0] %>, <%= coordinates[1] %>])
                            .addTo(map);
                        <% end %>
                    <% end %>

                    // Tracer les lignes entre les stations de départ et d'arrivée pour chaque vol
                    //console.log("Flight Paths:", <%= @flight_paths.to_json.html_safe %>);
                    <% @flight_paths.each do |path| %>
                        console.log("Tracing flight path for flight ID:", <%= path[:id] %>);
                        console.log("Coordinates:", <%= path[:coordinates].to_json %>);
                        map.addLayer({
                            id: 'route<%= path[:id] %>', // Utiliser l'ID du vol pour créer un ID de couche unique
                            type: 'line',
                            source: {
                                type: 'geojson',
                                data: {
                                    type: 'Feature',
                                    properties: {},
                                    geometry: {
                                        type: 'LineString',
                                        coordinates: <%= path[:coordinates].to_json %>
                                    }
                                }
                            },
                            layout: {
                                'line-join': 'round',
                                'line-cap': 'round'
                            },
                            paint: {
                                    'line-color': '#888',
                                    'line-width': 4,
                                    // Ici, nous définissons le motif de pointillé : [longueur du segment, longueur de l'espace]
                                    'line-dasharray': [1, 2] // 
                            }
                        });
                    <% end %>
                });
        </script>
        <span style ="position: absolute; top: 50%; left: 0; transform: translateY(-50%); margin-left: 150px;" ><%=link_to"HOME",root_path,class: "btn btn-primary" %></span> 
        </div>

</body> 

app/views/pages/home.html.erb
<body class="custom-background">
    <div class="container text-center">
        <div class="row my-4">
            <div class="col">
                <p class="airplus">AIR PLUS - OPERATIONS</p>
            </div>
        </div>

        <div class="row my-4 align-items-center justify-content-center">
            <div class="col-md-5">
                <%= link_to image_tag("B777.jpeg", alt: "B777", class: "img-fluid larger-image"), pages_operations_path %>
            </div>

            <div class="col-md-5">
                <div id='map' style='width: 600px; height: 500px; margin: auto;'></div>
            </div>
        </div>
    </div>

    <div class="map">
        <script>
            document.addEventListener("turbolinks:load", function() {
                mapboxgl.accessToken = 'pk.eyJ1IjoicG5nYXV0aGllciIsImEiOiJjbHFncjBjMG0xZGNlMm1ubWV2aXU1NnpmIn0.x06uuDfCgcRIZtJNmrF7Bg';
                var coordinates = [2.549324, 49.008468];
                var map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/mapbox/streets-v12',
                    center: coordinates,
                    zoom: 2
                });

                map.on('load', function() {
                    <% @stations_coordinates.each do |coordinates| %>
                        new mapboxgl.Marker({
                            scale: 0.6,
                            color: '#fc0339'
                        })
                        .setLngLat([<%= coordinates[0] %>, <%= coordinates[1] %>])
                        .addTo(map);
                    <% end %>

                    <% @flight_paths.each do |path| %>
                        map.addLayer({
                            id: 'route<%= path[:id] %>',
                            type: 'line',
                            source: {
                                type: 'geojson',
                                data: {
                                    type: 'Feature',
                                    properties: {},
                                    geometry: {
                                        type: 'LineString',
                                        coordinates: <%= path[:coordinates].to_json %>
                                    }
                                }
                            },
                            layout: {
                                'line-join': 'round',
                                'line-cap': 'round'
                            },
                            paint: {
                                'line-color': '#888',
                                'line-width': 4,
                                'line-dasharray': [1, 2]
                            }
                        });
                    <% end %>
                });
            });
        </script>
        <br>

        <div class="bigmap">
            <span><%= link_to "BIG MAP?", pages_bigmap_path, class: "btn btn-primary" %></span>
        </div>
        
    </div>
</body>

app/views/pages/operations.html.erb
<body class="background-color">
    <div class="container mt-5" id="mycontainer">
        <h2 class="text-center mb-4">Operating Aircrafts Specifications</h2>
        <table class="table table-striped table-bordered my-custom-background rounded-shadow">
            <thead class="thead-dark">
                <tr>
                    <th>Category</th>
                    <th>Create</th>
                    <th>List</th>
                </tr>
            </thead>
            <tbody id="test">
                <tr>
                    <td><strong>Airlines:</strong></td>
                    <td><%= link_to "Créer Airline codes", new_airline_code_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste Airline codes", airline_codes_path, class: "btn btn-info" %></td>
                </tr>
                <tr>
                    <td><strong>Network:</strong></td>
                    <td><%= link_to "Créer Réseau", new_haul_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste des réseaux", hauls_path, class: "btn btn-info" %></td>
                </tr>
                <tr>
                    <td><strong>Aircrafts:</strong></td>
                    <td><%= link_to "Créer type avion", new_aircraft_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste types avion", aircrafts_path, class: "btn btn-info" %></td>
                </tr>
                <tr>
                    <td><strong>Registrations:</strong></td>
                    <td><%= link_to "Créér des immatriculations", new_registration_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste des immatriculations", registrations_path, class: "btn btn-info" %></td>
                </tr>
                <tr>
                    <td><strong>Cabins:</strong></td>
                    <td><%= link_to "Créer cabins", new_cabin_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste des cabins", cabins_path, class: "btn btn-info" %></td>
                </tr>
                <tr>
                    <td><strong>Seats:</strong></td>
                    <td><%= link_to "Créer Seats number", new_seat_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste des Seats number", seats_path, class: "btn btn-info" %></td>
                </tr>
                <tr>
                    <td><strong>Stations:</strong></td>
                    <td><%= link_to "Créer Stations", new_station_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste stations", stations_path, class: "btn btn-info" %></td>
                </tr>

            </tbody>
        </table>
        <h2 class="text-center my-4">Operating Flights</h2>
        <table class="table table-striped table-bordered rounded-shadow">
            <thead class="thead-dark">
                <tr>
                    <th>Category</th>
                    <th>Create</th>
                    <th>List</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>Flight ops:</strong></td>
                    <td><%= link_to "Créer Flight ops", new_flight_path, class: "btn btn-success" %></td>
                    <td><%= link_to "Liste flights ops", flights_path, class: "btn btn-info" %></td>
                </tr>
                
                
            </tbody>
        </table>
        <div class="text-center mt-5">
            <%= link_to "Back Home Operations", pages_home_path, class: "btn btn-primary mx-2" %>
            <%= link_to "AIR PLUS front page", pages_airplus_path, class: "btn btn-primary mx-2" %>
        </div>
    </div>
</body>