config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/show'
  get 'customers/new'
  get 'customers/create'
  get 'customers/edit'
  get 'customers/update'
  get 'customers/destroy'
  get 'customers/book'
  get 'pages/bigmap', to: 'pages#bigmap'
  get 'pages/home', to: 'pages#home'
  get 'pages/operations', to: 'pages#operations'
  get 'pages/airplus', to: 'pages#airplus'
  get 'flights/stations', to: 'flights#stations'
  get 'geocoding/show', to: 'geocoding#show'
  get 'geocoding/geocode', to: 'geocoding#geocode'
  get 'flights/index'
  get 'flights/show'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/destroy'
  get 'flights/update'
  get 'registrations/index'
  get 'registrations/show'
  get 'registrations/new'
  get 'registrations/create'
  get 'registrations/edit'
  get 'registrations/update'
  get 'registrations/destroy'
  get 'pages/operations'
  get 'flights/available_registrations', to: 'flights#available_registrations'
  get 'flights/available_aircrafts', to: 'flights#available_aircrafts', as: 'flights_available_aircrafts'
  get 'customers/list', to: 'customers#list', as: 'customers_list'
  get 'flights/:flight_id/customers', to: 'customers#flight_customers', as: 'flight_customers'
 
  root to: 'pages#airplus'
 

  resources :aircrafts
  resources :cabins
  resources :seats
  resources :registrations
  resources :flights
  resources :hauls
  resources :stations
  resources :airline_codes
  resources :customers

   post 'customers/reset_search', to: 'customers#reset_search'
 
  resources :flights do
    member do
      post 'create_return'
    end
  end

  resources :flights do
    collection do
      get :available_aircrafts
    end
  end

  

  
  
end

app/models/airline_code.rb
class AirlineCode < ApplicationRecord
    before_validation :upcase_code
    validate :unique_code
    validates :code, length: { within: 2..2 }
    validates :code, presence: true
    has_many :flights, dependent: :destroy




    private

    def unique_code
       existing_code = AirlineCode.pluck(:code) # Récupère tous les numéros existants dans la base de données
       pp "test" *100
       if existing_code.include?(code)
         errors.add(:code, ":  Le code #{self.code} est déjà utilisé.")
       end
     end

     def upcase_code
       self.code = code.upcase if code.present?
     end 




end

app/controllers/airline_codes_controller.rb
class AirlineCodesController < ApplicationController
    before_action :set_airline_code, only: [:show, :destroy]
  
    def index 
      @airline_codes = AirlineCode.all
    end 
  
    def show
      # @airline_code is set by the set_airline_code before_action
    end
  
    def new 
      @airline_code = AirlineCode.new
      @airline_codes = AirlineCode.all
    end 
  
    def create 
      @airline_code = AirlineCode.new(airline_code_params)
      if @airline_code.save
        redirect_to @airline_code, notice: "Airline code créé"
      else
        render :new
      end
    end 
  
    def destroy
      if @airline_code.flights.any?
        flash[:alert] = "This airline code is used by flights and cannot be deleted."
        else
          @airline_code.destroy
          flash[:notice] = "Airline code was successfully deleted."
      end
      redirect_to airline_codes_url
    end
  
    private
  
    def set_airline_code
      @airline_code = AirlineCode.find(params[:id])
    end
  
    def airline_code_params
      params.require(:airline_code).permit(:code)
    end
  end
  

app/helpers/airline_codes_helper.rb
module AirlineCodesHelper
end

app/views/airline_codes/index.html.erb
<div class="container mt-10">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <td>Airline code</td>
                </tr>
            </thead>
            <tbody>
                <% @airline_codes.each do |airline_code| %>
                <tr>
                    <td><%= airline_code.code %></td>
                    <td>
                        <%= link_to "Delete Airline Code", airline_code_path(airline_code), method: :delete, class: "btn btn-danger btn-margin" %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>

        <span><%= link_to "Home", pages_operations_path, class: "btn btn-primary" %></span>
    </div>
</div>

app/views/airline_codes/new.html.erb
<div class="container col-12">
    <div class="bordered">
      
        <% if @airline_codes.present? %>

                    <h4>Code(s) déjà créés :</h4>
                        <td><%= @airline_codes.map(&:code).join(', ') %></td>
        <%else%>
                <div class="alert alert-danger">
                    No airline code, create it.
                   
                </div>
        <% end %>
    </div>
     <div>
           <% if @airline_code.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@airline_code.errors.count, "error") %> </h2>
                    <ul>
                        <% @airline_code.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
     </div>   
<div class="int1">
<h1>Create Airline code</h1>
</div>
<div class="row">
   <div class="col-3 mt-5">
    <%= simple_form_for(@airline_code) do |f| %>
        <div class="col-2.5">
            <%=  f.label :code,content_tag(:strong, 'Airline code:') %>
            <%=  f.text_field :code, class:"rounded-box"%>
        </div>
        <br><br>
            <div class="submit">
                <%=f.submit"Valider", class: "btn btn-primary"%>
            </div>   
            <br><br>
            <span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 
    <%end%>
</div>








</div>

app/views/airline_codes/show.html.erb
<div class="container">
    <p> <strong>Airline code  = </strong> <%= @airline_code.code %></p>
</div>
<span><%=link_to"Home",pages_operations_path,class: "btn btn-primary" %></span> 